name = "a0b_usb_mass_storage_ufi"
description = "A0B: USB Mass Storage UFI"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "usb", "mass_storage", "ufi"]

project-files = ["gnat/a0b_usb_mass_storage_ufi.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
